stages:
  - build-pages
  - deploy-pages

include:
  - project: "aao-fyi/pipelines"
    file: "hugo/.hugo-build-ci.yml"

variables:
  # build-pages
  HUGO_SOURCE_DIR: ""
  # Cloudflare variables
  CLOUDFLARE_API_TOKEN: ""
  CLOUDFLARE_ACCOUNT_ID: ""
  # Project variables
  CF_PAGES_PROJECT: ""
  CF_PAGES_BRANCH: $CI_COMMIT_BRANCH

deploy-pages:
  stage: deploy-pages
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  # Install dependencies
  before_script:
    # Install Go, Git, NPM
    - apk add --update --no-cache npm
    # Install Cloudflare Wrangler
    - npm install -g wrangler
  # Deploy project
  script:
    # Direct upload Hugo `public` output to Cloudflare Pages
    - wrangler pages deploy ./public --project-name=$CF_PAGES_PROJECT --branch=$CF_PAGES_BRANCH
