image: registry.gitlab.com/pages/hugo/hugo_extended:latest

stages:
  - build
  - deploy

variables:
  # Cloudflare variables
  CLOUDFLARE_API_TOKEN: ""
  CLOUDFLARE_ACCOUNT_ID: ""
  # Project variables
  CF_PAGES_PROJECT: ""
  CF_PAGES_BRANCH: $CI_COMMIT_BRANCH
  HUGO_SOURCE_DIR: ""

build:
  stage: build
  # Install dependencies
  before_script:
    # Install Go, Git, NPM
    - apk add --update --no-cache git go npm
    # Install project NPM dependencies
    - |
      if [ -f package.json ]; then
        npm ci
      fi
  # Build project
  script:
    # Hugo build
    - |
      if [ -n "$HUGO_SOURCE_DIR" ]; then
        hugo -s "$HUGO_SOURCE_DIR"
        mv "$HUGO_SOURCE_DIR/public" ./public
      else
        hugo
      fi
  # Export build
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  # Install dependencies
  before_script:
    # Install Go, Git, NPM
    - apk add --update --no-cache npm
    # Install Cloudflare Wrangler
    - npm install -g wrangler
  # Deploy project
  script:
    # Direct upload Hugo `public` output to Cloudflare Pages
    - wrangler pages deploy ./public --project-name=$CF_PAGES_PROJECT --branch=$CF_PAGES_BRANCH
