image: registry.gitlab.com/pages/hugo/hugo_extended:latest

stages:
  - deploy

pages:
  stage: deploy
  # Install dependencies
  before_script:
    # Install Go, Git, NPM
    - apk add --update --no-cache git go npm
    # Install project NPM dependencies
    - |
      if [ -f package.json ]; then
        npm ci
      fi
  # Build project
  script:
    # Hugo build
    - hugo
  # Export build
  artifacts:
    paths:
      - public
