image: registry.gitlab.com/pages/hugo/hugo_extended:latest

stages:
  - build-pages
  - warn-depreciated

include:
  - project: "aao-fyi/pipelines"
    file: "hugo/.hugo-build-ci.yml"

warn-depreciated:
  stage: warn-depreciated
  script:
    - echo "This CI/CD pipeline is DEPRECIATED, switch from `hugo/.gl-pages-deploy-ci.yml` to `hugo/.hugo-build-ci.yml` in the same `aao-fyi/pipelines` project for continued functionality. This pipeline ran as an alias for that pipeline on this job." && exit 1
